// export const ROLES = {
//   OWNER: 'OWNER',
//   ADMIN: 'ADMIN',
//   MEMBER: 'MEMBER',
// } as const;

// export type Role = (typeof ROLES)[keyof typeof ROLES];


// export const PERMISSIONS = {
//   // Workspace
//   WORKSPACE_EDIT: 'WORKSPACE_EDIT',
//   WORKSPACE_DELETE: 'WORKSPACE_DELETE',
//   WORKSPACE_INVITE_MEMBER: 'WORKSPACE_INVITE_MEMBER',
//   WORKSPACE_EDIT_INVITE_LINK: 'WORKSPACE_EDIT_INVITE_LINK',

//   // Project
//   PROJECT_CREATE: 'PROJECT_CREATE',
//   PROJECT_UPDATE: 'PROJECT_UPDATE',
//   PROJECT_DELETE: 'PROJECT_DELETE',
//   PROJECT_EXPORT_DATA: 'PROJECT_EXPORT_DATA',

//   PROJECT_ADD_MEMBER: 'PROJECT_ADD_MEMBER',
//   PROJECT_REMOVE_MEMBER: 'PROJECT_REMOVE_MEMBER',

//   // Task
//   TASK_CREATE: 'TASK_CREATE',
//   TASK_ASSIGN: 'TASK_ASSIGN',
//   TASK_UPDATE: 'TASK_UPDATE',
//   TASK_DELETE: 'TASK_DELETE',
//   TASK_UPDATE_DUE_DATE: 'TASK_UPDATE_DUE_DATE',
// } as const;

// export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];


// export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
//   [ROLES.OWNER]: [
//     PERMISSIONS.WORKSPACE_EDIT,
//     PERMISSIONS.WORKSPACE_DELETE,
//     PERMISSIONS.WORKSPACE_INVITE_MEMBER,
//     PERMISSIONS.WORKSPACE_EDIT_INVITE_LINK,

//     PERMISSIONS.PROJECT_CREATE,
//     PERMISSIONS.PROJECT_UPDATE,
//     PERMISSIONS.PROJECT_DELETE,
//     PERMISSIONS.PROJECT_ADD_MEMBER,
//     PERMISSIONS.PROJECT_REMOVE_MEMBER,
//     PERMISSIONS.PROJECT_EXPORT_DATA,

//     PERMISSIONS.TASK_CREATE,
//     PERMISSIONS.TASK_ASSIGN,
//     PERMISSIONS.TASK_UPDATE,
//     PERMISSIONS.TASK_DELETE,
//     PERMISSIONS.TASK_UPDATE_DUE_DATE,
//   ],

//   [ROLES.ADMIN]: [
//     PERMISSIONS.PROJECT_CREATE,
//     PERMISSIONS.PROJECT_UPDATE,
//     PERMISSIONS.PROJECT_DELETE,
//     PERMISSIONS.PROJECT_ADD_MEMBER,
//     PERMISSIONS.PROJECT_REMOVE_MEMBER,

//     PERMISSIONS.TASK_CREATE,
//     PERMISSIONS.TASK_ASSIGN,
//     PERMISSIONS.TASK_UPDATE,
//     PERMISSIONS.TASK_DELETE,
//     PERMISSIONS.TASK_UPDATE_DUE_DATE,
//   ],

//   [ROLES.MEMBER]: [
//     PERMISSIONS.TASK_CREATE,
//     PERMISSIONS.TASK_UPDATE,
//     PERMISSIONS.TASK_UPDATE_DUE_DATE,
//   ],
// } as const;
